services:
  - type: worker
    name: smart-ai-scanner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11.9
    autoDeploy: true
